kind: pipeline
name: default
steps:
- name: test
  image: python:3
  environment:
     CC_TEST_REPORTER_ID:
         from_secret: cc_token_id
  commands:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "cc-test-reporter"
  - chmod +x "cc-test-reporter"
  - pip install -r requirements.txt
  - coverage run test_app.py
  - coverage lcov
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage.lcov
  - ./cc-test-reporter upload-coverage
  when:
    event:
    - pull_request

